workspace:
  base: /node
  path: drone/node-example

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  ssh:
    image: appleboy/drone-ssh
    host:
      - 128.199.179.216
    username: root
    secrets: [ ssh_key ]
    script:
      - echo "Hi I am appleboy"
      - touch appleboy.txt
