workspace:
  base: /node
  path: drone/node-example

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  frontend:
    image: node:8.3.0
    commands:
      - sleep 5
      - yarn install
      - ./node_modules/.bin/mocha
      - node redis.js

services:
  cache:
    image: redis
