workspace:
  base: /node
  path: drone/node-example

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  frontend:
    image: node:8.3.0
    commands:
      - echo "test frontend"

  backend:
    image: node:8.3.0
    commands:
      - echo "test backend"
