workspace:
  base: /node
  path: drone/node-example

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  publish:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ latest ]
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
